### Charity API
apiVersion: v1
kind: Pod
metadata:
  name: sharecare-charity
  labels:
    purpose: sharecare-app
    app: backend-api
spec:
  containers:
  - name: charity-api
    image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-charity:latest
    env:
    - name: DATABASE_HOST
      value: "35.195.26.117" 
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "charity"
    - name: DATABASE_USERNAME
      value: "postgres"
    - name: DATABASE_PASSWORD
      value: "hackPassword1!"
---
### Media API
apiVersion: v1
kind: Pod
metadata:
  name: sharecare-media
  labels:
    purpose: sharecare-app
    app: backend-api
spec:
  containers:
  - name: media-api
    image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-media:latest
    env:
    - name: DATABASE_HOST
      value: "35.195.26.117"
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "media"
    - name: DATABASE_USERNAME
      value: "postgres"
    - name: DATABASE_PASSWORD
      value: "hackPassword1!"
---
### POST API
apiVersion: v1
kind: Pod
metadata:
  name: sharecare-post
  labels:
    purpose: sharecare-app
    app: backend-api
spec:
  containers:
  - name: post-api
    image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-post:latest
    env:
    - name: DATABASE_HOST
      value: "35.195.26.117" 
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "post"
    - name: DATABASE_USERNAME
      value: "postgres"
    - name: DATABASE_PASSWORD
      value: "hackPassword1!"
---
### User API
apiVersion: v1
kind: Pod
metadata:
  name: sharecare-user
  labels:
    purpose: sharecare-app
    app: backend-api
spec:
  containers:
  - name: user-api
    image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-user:latest
    env:
    - name: DATABASE_HOST
      value: "35.195.26.117" 
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "user"
    - name: DATABASE_USERNAME
      value: "postgres"
    - name: DATABASE_PASSWORD
      value: "hackPassword1!"
---
### Front End Web App
### hit me at: 130.211.106.19:80
apiVersion: v1
kind: Pod
metadata:
  name: sharecare-frontend
  labels:
    purpose: sharecare-app
    app: frontend-service
spec:
  containers:
  - name: charity-api
    image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-web:latest
    env:
    - name: DATABASE_HOST
      value: "35.195.26.117" 
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: "charity"
    - name: DATABASE_USERNAME
      value: "postgres"
    - name: DATABASE_PASSWORD
      value: "hackPassword1!"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer  #gives us an external IP address
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  #gives us an external IP address
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

      #curl 34.76.10.56/charities
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
# spec:
#   type: LoadBalancer  #gives us an external IP address
#   selector:
#     app: frontend-api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-api
# spec:
#   type: LoadBalancer  #gives us an external IP address
#   selector:
#     app: backend-api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000

      #curl 130.211.106.19:80/charities
      # k apply -f charity-pod.yml  