### FRONT-END
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecare-frontend
  labels:
    app: frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
      - name: frontend-api
        image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-web:latest
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  type: LoadBalancer  #gives us an external IP address
  selector:
    app: frontend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000