apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: web-frontend-service
          servicePort: 80
        path: /
      - backend:
          serviceName: charity-api-service 
          servicePort: 80
        path: /charities
      - backend:
          serviceName: user-api-service 
          servicePort: 80
        path: /users
      - backend:
          serviceName: media-api-service
          servicePort: 80
        path: /media
      - backend:
          serviceName: post-api-service  
          servicePort: 80
        path: /posts
