### POST API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecare-post
  labels:
    app: post-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
      - name: post-api
        image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-post:latest
        env:
        - name: DATABASE_HOST
          value: "35.195.26.117" 
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "post"
        - name: DATABASE_USERNAME
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "hackPassword1!"
        - name: MEDIA_SERVICE_URL
          value: "http://media-api-service"
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            host:
            scheme: HTTP
            path: /posts
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: post-api-service
spec:
  type: NodePort  #gives us an external IP address
  selector:
    app: post-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000