### FRONT-END
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharecare-frontend
  labels:
    app: frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-api
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
      - name: frontend-api
        image: eu.gcr.io/lloyds-hackathon-team-1/sharecare-web:latest
        env:
        - name: BASE_URL
          value: "http://34.149.119.94"
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  type: NodePort  #clusterIP, gives it an internal IP, for loadbalancing from ingress
  selector:
    app: frontend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000